### ISSUE TITLE
Selective Sweep?

### ISSUE THREAD

**Issue by sherzberg** [adamdecaf/gist-sweep#1]
This looks like it sweeps all-the-things. I have some private and public gists that I want to keep. Have any care to support selectively sweeping gists like by a naming convention?

**Comment by adamdecaf** [comment]
@sherzberg Are you thinking along the lines of y/n for each gist (where it shows the name of the gist) or filters?

``` shell
$ gist-sweep -u adamdecaf *pattern*
```

**Comment by sherzberg** [comment]
@adamdecaf i like supplying a pattern.

**Comment by adamdecaf** [comment]
@sherzberg Yea, I can try and get something going. It probably would be good to list the names of the gists that are going to be deleted also.

**Comment by adamdecaf** [comment]
@sherzberg Could you clone this repo down and run `rake install` to try out the pattern matching? Here's an example of it at work!

``` shell
~/src/mine/gist-sweep $ gist-sweep -u adamdecaf -v example
Removing gists older than 2015-02-08T10:51:48-05:00
4e37c8123c6c71d76d33 -- example-gist
Remove 1 gists? (y/n) y
Deleting gist 4e37c8123c6c71d76d33
Swept gists.
```

**Comment by adamdecaf** [comment]
If it works I can cut a release with it!
